services:
  postgres:
    container_name: postgres-sql-dl
    image: postgres
    environment:
      POSTGRES_USER: matine
      POSTGRES_PASSWORD: matine
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: deco_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-dl
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local