spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deco_lab
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: abdelmatine.sfar@esprit.tn
    password: nwducguzttgkvrfd
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          trust: "*"
          enable: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    protocol: smtp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/ktebi-tn"
          
application:
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088